### ISSUE TITLE
Zombie processes not reaped

### ISSUE THREAD

**Issue by raxod502** [radian-software/sleeping-beauty#1]
Using sleepingd as pid1 in a docker container fails to reap zombie processes per https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/. Either we need to implement this or (more likely) we need to include phusion's pid1 in the release docker image and recommend its usage in any downstream application that uses sleepingd.

**Comment by Nick-Triller** [comment]
[tini](https://github.com/krallin/tini) and [dumb-init](https://github.com/Yelp/dumb-init) are some potential alternatives to phusion's pid1.

**Comment by raxod502** [comment]
Good call. We now use tini for integration tests, and I will update the README to recommend its usage in production as well. https://github.com/radian-software/sleeping-beauty/blob/7693fc5a6cc2f9850fbd1e1e6f72f457663bc3bb/test/integration/run_in_docker.bash#L26-L29
